# Workshop specific values
####################################################
# Compute Canada: Graham + SLURM
# 
host_name: "Graham"
host_login: "graham.computecanada.ca"
host_location: "University of Waterloo"
host_homedir: "/home"
host_prompt: "[yourUsername@gra-login1 ~]$"
local_prompt: "[user@laptop ~]$"
sched_name: "SLURM"
sched_submit: "sbatch"
sched_submit_options: ""
sched_status: "squeue"
sched_flag_user: "-u yourUsername"
sched_del: "scancel"
sched_interactive: "srun"
sched_flag_interactive: ""
sched_info: "sinfo"
sched_comment: "#SBATCH"
sched_flag_name: "-J"
sched_hist: "sacct -u yourUsername"
sched_flag_histdetail: "-l -j"
