# EPCC, The University of Edinburgh: ARCHER + PBS Pro
host_name: "ARCHER"
host_hostname: "eslogin001"
host_login: "login.archer.ac.uk"
host_location: "EPCC, The University of Edinburgh
host_homedir: "/home/tc011/tc011/lola/"
host_workdir: "/work/tc011/tc011/lola/"
host_prompt: "[yourUsername@eslogin001 ~]$"
local_prompt: "[user@laptop ~]$"
sched_name: "PBS Pro"
sched_submit: "qsub"
sched_submit_options: "-A tc011 -q R7090776"
sched_submitiopt: "-A tc011 -q R7090776 -IVl select=1,walltime=0:5:0"
sched_status: "qstat"
sched_flag_user: "-u yourUsername"
sched_del: "qdel"
sched_interactive: "qsub"
sched_flag_interactive: "-IVl select=1"
sched_info: "pbsnodes -a"
sched_comment: "#PBS"
sched_flag_name: "-N"
sched_hist: "qstat -x"
sched_flag_histdetail: "-f"
