# EPCC, The University of Edinburgh: Cirrus + PBS Pro
host_name: "Cirrus"
host_login: "login.cirrus.ac.uk"
host_location: "EPCC, The University of Edinburgh"
host_homedir: "/lustre/home/tc001/lola"
host_prompt: "[yourUsername@cirrus-login0 ~]$"
local_prompt: "[user@laptop ~]$"
sched_name: "PBS Pro"
sched_submit: "qsub"
sched_submit_options: "-A tc001 -q R387726"
sched_status: "qstat"
sched_flag_user: "-u yourUsername"
sched_del: "qdel"
sched_interactive: "qsub"
sched_flag_interactive: "-IVl select=1:ncpus=1"
sched_info: "pbsnodes -a"
sched_comment: "#PBS"
sched_flag_name: "-N"
sched_hist: "qstat -x"
sched_flag_histdetail: "-f"
