# EPCC, The University of Edinburgh: ARCHER + PBS Pro
host_name: "ARCHER"
host_hostname: "eslogin001"
host_login: "login.archer.ac.uk"
host_location: "EPCC, The University of Edinburgh
host_homedir: "/home/tc011/tc011/yourUsername/"
host_workdir: "/work/tc011/tc011/yourUsername/"
host_prompt: "yourUsername@eslogin001:~>"
local_prompt: "user@laptop:~$"
sched_name: "PBS Pro"
sched_submit: "qsub"
sched_submit_options: "-q R7090776"
sched_submit_options_long: "-q R7090776 -A tc011 -l select=1,walltime=0:10:0"
sched_submitiopt: "-q R7090776 -A tc011 -IVl select=1,walltime=0:10:0"
sched_status: "qstat"
sched_flag_user: "-u yourUsername"
sched_del: "qdel"
sched_interactive: "qsub"
sched_flag_interactive: "-IVl select=1"
sched_info: "pbsnodes -a"
sched_comment: "#PBS"
sched_flag_name: "-N"
sched_hist: "qstat -x"
sched_flag_histdetail: "-f"
